config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: 'events#index'
  resources :events do
    resources :tickets, only: [:new, :create]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_users, dependent: :destroy
  has_many :users, through: :event_users, dependent: :destroy

  validates :title, presence: true
  validates :datetime, presence: true

  mount_uploader :image, ImageUploader

  def self.search(search)
    return Event.all unless search
    Event.where('title LIKE(?)', "%#{search}%")
  end
end

app/models/event_user.rb
class EventUser < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :event_users, dependent: :destroy
  has_many :events, through: :event_users, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  def self.guest
    find_or_create_by!(name: 'ゲスト', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
before_action :set_event, only: [:show, :edit]

  def index
    @events = Event.all.order(datetime: "ASC").page(params[:page]).per(7)
  end

  def new
    @event = Event.new
    @event.users << current_user
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to root_path, notice: '勉強会が作成されました'
    else
      flash.now[:alert] = '必須項目を入力してください。'
      render :new
    end
  end

  def show
  end

  def search
    @events = Event.search(params[:keyword])
  end

  def edit
  end

  def update
    event = Event.find(params[:id])
    if event.update(event_params)
      redirect_to root_path, notice: '勉強会を編集しました'
    else
      render :edit
    end
  end

  def destroy
    event = Event.find(params[:id])
    if event.destroy
      redirect_to root_path, notice: '勉強会を削除しました'
    else
      render :edit
    end
  end

  private
  def event_params
    params.require(:event).permit(:name, :title, :datetime, :image, :content, :tag, user_ids: []).merge(user_id: current_user.id)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: %i[update destroy]

  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの編集・削除できません。'
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.haml
.Eventlist
  .Eventlist__left
    .datetime
      .datetime__date
        = event.datetime.strftime("%m月%d日")
      .datetime__time
        = event.datetime.strftime("%H:%M")
  .Eventlist__right
    .event-owner
      .eventowner
        .eventowner__title
          主催者：
        .eventowner__name
          = event.name
      .eventowner
        .eventowner__created-title
          公開日：
        .eventowner__created-date
          = event.created_at.strftime("%m月%d日")
    .event-content
      .event-content__image
        - if event.image?
          = image_tag event.image.url, :size =>'240x130'
      .event-content__title
        = link_to event.title, event_path(event.id)
    .event-member
      .event-member__header
        参加者：
      -# .event-member__list
      -#   - event.users.each do |e|
      -#     = e.name

app/views/events/edit.html.haml
.Event-Box
  .Eventbox
    .Eventbox__Info
      = form_with model: @event, locale: true do |f|
        %h2.Eventbox-heading 勉強会を編集
        .form-group.col-md-8
          = f.label :name, '主催者'
          = f.text_field :name, class: 'form-control'
        .form-group.col-md-8
          = f.label :title, 'タイトル'
          = f.text_field :title, class: 'form-control', placeholder: '例： Rails勉強会'
        .form-group.col-md-8
          = f.label :datetime, '日時'
          = f.datetime_local_field :datetime, class: 'form-control'
        .form-group.col-md-6
          = f.label :image, "イベント画像"
          = f.file_field :image, class: 'form-control'
        .form-group.col-md-8
          = f.label :content, "勉強会の内容"
          = f.text_area :content, class: 'form-control'
        .form-group.col-md-6
          = f.label :tag, "言語"
          = f.text_field :tag, size: 10*20 ,class: 'form-control'
        .form-group.col-md-6
          = f.submit '編集完了', class: 'btn btn-primary'

app/views/events/index.html.haml
.wrapper
  .Main-Contents
    .Contents-box
      .Contents-header
        .EventInfo
          近日開催の勉強会
        .EventInfo__date
      .Eventlists
        - @events.each do |event|
          = render partial: "event", locals: { event: event }
      = paginate @events

app/views/events/new.html.haml
.Event-Box
  .Eventbox
    .Eventbox__Info
      = form_with model: @event, local: true do |f|
        %h2.Eventbox-heading 勉強会を作成
        .form-group.col-md-8
          = f.label :name, '主催者'
          %span.badge.badge-danger
            必須
          = f.text_field :name, class: 'form-control'
        .form-group.col-md-8
          = f.label :title, 'タイトル'
          %span.badge.badge-danger
            必須
          = f.text_field :title, class: 'form-control', placeholder: '例： Rails勉強会'
        .form-group.col-md-8
          = f.label :datetime, '日時'
          %span.badge.badge-danger
            必須
          = f.datetime_local_field :datetime, class: 'form-control'
        .form-group.col-md-6
          = f.label :image, "イベント画像"
          = f.file_field :image, class: 'form-control'
        .form-group.col-md-8
          = f.label :content, "勉強会の内容"
          = f.text_area :content, class: 'form-control'
        -# .form-group.col-md-6
        -#   = f.label :tag, "タグ"
        -#   = f.text_field :tag, size: 10*20 ,class: 'form-control'
        -# .form-check
        -#   = f.label "参加者", class: "form-check-label"
        -#   = f.collection_check_boxes :user_ids, User.all, :id, :name, class: "form-check-input"
        .form-group
          = f.submit '勉強会を作成', class: 'btn btn-primary'

app/views/events/search.html.haml
.wrapper
  .Main-Contents
    .Contents-box
      .Eventlists
        - @events.each do |event|
          = render partial: "event", locals: { event: event }

app/views/events/show.html.haml
.Event-Box
  .Event-Info
    .Event-Info__header
      .imagebox
        -if @event.image?
          = image_tag @event.image.url, :size =>'500x250'
      .Eventjoin-box
        .Eventjoin-box__date
          = @event.datetime.strftime("%Y年%m月%d日")
        - if user_signed_in? && current_user.email != "guest@example.com"
          .Eventjoin-box__form
            - unless current_user.id == @event.user_id
              = link_to "勉強会に申し込む", new_event_ticket_path(current_user)
        - if user_signed_in? && current_user.id == @event.user_id
          .Event-edit
            = link_to "編集", edit_event_path(@event.id), method: :get
          .Event-destroy
            = link_to "削除", event_path(@event.id),method: :delete
    .Event-Info__titlebox
      .title-info
        タイトル：
      .title
        = @event.title
    .Event-Info__contentbox
      .content-Info
        勉強会内容：
      .content
        = @event.content
    .Event-Info__memberlist
      .title
        参加者：
      .member
        - @event.users.each do |event|
          = event.name

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Terakoya
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .Header
      .Header__title
        = link_to "TERAKOYA", root_path, class: "header-logo"
        .searchform
          - if user_signed_in?
            = form_with(url: search_events_path, local: true, method: :get) do |f|
              = f.text_field :keyword, placeholder: "勉強会を検索する", class: "search-input"
              = f.submit "検索", class: "search-btn"
      - if user_signed_in? && current_user.email != "guest@example.com"
        .Header__nav
          .nav-list
            = link_to do
              = icon('fas', 'edit')
            = link_to "勉強会作成", new_event_path
          .nav-list
            = link_to do
              = icon('far', 'calendar')
            = link_to "参加一覧", user_path(current_user)
          .nav-list
            = link_to do
              = icon('fas', 'user')
            = link_to current_user.name, edit_user_registration_path(current_user)
      - elsif user_signed_in?
        .Header__nav
          .nav-list
            = link_to do
              = icon('fas', 'user')
            = link_to current_user.name, edit_user_registration_path(current_user)
    = render 'layouts/notifications'
    = yield